import { Button, Typography, buttonClasses } from '@mui/material';
import { Stack } from '@mui/system';
import { Link } from 'react-router-dom';
import Grid from '@mui/system/Unstable_Grid';
import CardMembershipIcon from '@mui/icons-material/CardMembership';
import BuildIcon from '@mui/icons-material/Build';
import WarningIcon from '@mui/icons-material/Warning';
import QrCode2Icon from '@mui/icons-material/QrCode2';
import RedeemIcon from '@mui/icons-material/Redeem';
import EmojiEventsIcon from '@mui/icons-material/EmojiEvents';

const items = [
  {
    icon: <CardMembershipIcon />,
    title: 'Certified Instructors',
    subtitle: 'List of ISA Certified instructors',
    route: '/certified-instructors',
  },
  {
    icon: <RedeemIcon />,
    title: 'Certified Riggers',
    subtitle: 'List of ISA Certified riggers',
    route: '/certified-riggers',
  },
  {
    icon: <BuildIcon />,
    title: 'Gear Certificates',
    subtitle: 'List ISA Certified gears',
    route: '/instructor-certificates',
  },
  {
    icon: <WarningIcon />,
    title: 'Equipment Warnings',
    subtitle: 'Warnings and recalls for slackline equipments',
    route: '/equipment-warnings',
  },
  {
    icon: <QrCode2Icon />,
    title: 'QR Code Validator',
    subtitle: 'Validate QR codes generated by ISA',
    route: '/verify',
  },
  // {
  //   icon: <EmojiEventsIcon />,
  //   title: 'World Records',
  //   subtitle: 'Officialy recognized world records',
  //   route: '/world-records',
  //   disabled: true,
  // },
];

export function Homepage() {
  const sx = {
    [`& .${buttonClasses.startIcon} > *:nth-of-type(1)`]: {
      fontSize: '30px',
      mr: 2,
    },
    textTransform: 'none',
    width: '100%',
    justifyContent: 'flex-start',
  };

  return (
    <Grid container spacing={4}>
      {items.map((item) => (
        <Grid xs={12} lg={4} key={item.route}>
          <Button
            component={Link}
            to={item.route}
            variant="contained"
            sx={sx}
            startIcon={item.icon}
          >
            <Stack direction="column" spacing={0} sx={{ textAlign: 'left' }}>
              <Typography variant="body2Bold">{item.title}</Typography>
              <Typography variant="body2" sx={{ fontSize: '0.66rem' }}>
                {item.subtitle}
              </Typography>
            </Stack>
          </Button>
        </Grid>
      ))}
    </Grid>
  );
}
